fix menu item validation
monsieurbiz/SyliusMenuPlugin pull request #24
Opened 2022-10-05 15:07 UTC by jacquesbh

- Use TextType for URL
- Update URL validations

2022-10-05 15:14 UTC, delyriand approved these changes

2022-10-05 15:30 UTC, lanfisis requested changes

2022-10-05 15:30 UTC, lanfisis commented on src/Resources/config/validation/MenuItemTranslation.yaml
> +                    message: 'This value is not a valid URL (absolute or relative) or a valid hashtag.'
Why did you don't use a key as usual ?

2022-10-05 15:41 UTC, lanfisis approved these changes

2022-10-05 15:46 UTC, delyriand approved these changes

2022-10-10 08:12 UTC, maximehuran approved these changes

2022-10-27 14:21 UTC, merged